background = #ffffff
foreground = #1d1d1f
selection-background = #dae9fc
selection-foreground = #1d1d1f
cursor-color = #1d1d1f
cursor-text = #ffffff
font-family = Menlo
font-size = 14
window-padding-x = 4
window-padding-y = 4
scrollback-limit = 10000000
shell-integration = none
term = xterm-256color
clipboard-read = deny
clipboard-write = ask
confirm-close-surface = false
keybind = super+w=unbind
palette = 0=#1d1d1f
palette = 1=#b42318
palette = 2=#247238
palette = 3=#8a5b00
palette = 4=#005fc4
palette = 5=#8945a6
palette = 6=#007880
palette = 7=#d5d5da
palette = 8=#64646b
palette = 9=#ce3025
palette = 10=#258142
palette = 11=#986800
palette = 12=#0070df
palette = 13=#9b43b4
palette = 14=#00838c
palette = 15=#ffffff
